name: "Pull Request Labeler"
on:
  pull_request_target:
    types: [opened, reopened]

permissions:
  contents: read

jobs:
  labeler:
    permissions:
      pull-requests: write # Labeler needs to be able to add labels to PRs.
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10 # v2.8.0
      with:
        egress-policy: audit

    - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
